import type { Metadata } from 'next';
import { convertUnits, hasSimpleRatio } from '@/domain/conversion/engine';
import { formatNumber } from '@/domain/conversion/format';
import type { ConversionPair } from '@/types/conversion';
import type { CategoryDefinition, CollectionDefinition, UnitDefinition } from '@/types/units';
import { absoluteUrl, siteConfig } from '@/lib/site';
import { buildFormula } from './formula';
import { pairPhrase, unitHeadingName } from './labels';

/**
 * Metadata generation.
 *
 * Every title, description and canonical URL is derived from the data model,
 * so a new unit or category gets correct metadata with no extra work and no
 * page can ship with a placeholder. Descriptions lead with the page's own exact
 * relationship or formula, which is what makes them genuinely unique rather
 * than a template with the unit names swapped (SEO_SPEC §5, §13).
 */

interface PageMetaInput {
  title: string;
  description: string;
  /** Site-relative canonical path, e.g. "/length/meters-to-feet". */
  path: string;
  /** Set for pages that should stay out of the index, such as search results. */
  noIndex?: boolean;
  /** Use the title as-is, without the site-name suffix. For the homepage. */
  absoluteTitle?: boolean;
}

/**
 * The site-wide sharing image generated by app/opengraph-image.tsx.
 *
 * Referenced explicitly: a page that sets its own `openGraph` object replaces
 * the inherited file-based image, so without this only the homepage would
 * carry one.
 */
const SOCIAL_IMAGE = {
  url: '/opengraph-image.png',
  width: 1200,
  height: 630,
  alt: `${siteConfig.name} — free online unit converter with formulas and reference tables`,
};

export function buildMetadata({
  title,
  description,
  path,
  noIndex,
  absoluteTitle,
}: PageMetaInput): Metadata {
  const url = absoluteUrl(path);

  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: 'website',
      title,
      description,
      url,
      siteName: siteConfig.name,
      locale: siteConfig.locale.replace('-', '_'),
      images: [SOCIAL_IMAGE],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [SOCIAL_IMAGE.url],
    },
    ...(noIndex ? { robots: { index: false, follow: true } } : {}),
  };
}

/** Words that stay lowercase inside a title. */
const MINOR_WORDS = new Set(['a', 'an', 'and', 'in', 'of', 'per', 'the', 'to']);

function titleCase(text: string): string {
  return text
    .split(' ')
    .map((word, index) => {
      if (index > 0 && MINOR_WORDS.has(word)) return word;
      // Words that already carry capitals (US, BTU, Celsius) stay as written.
      if (/[A-Z]/.test(word)) return word;
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(' ');
}

/**
 * The exact relationship for one unit of `from`, used in descriptions and in
 * the page's opening statement.
 */
export function oneUnitStatement(from: UnitDefinition, to: UnitDefinition): string | null {
  const result = convertUnits(1, from, to);
  if (!result.ok) return null;
  return `1 ${from.name} = ${formatNumber(result.value)} ${
    Math.abs(result.value) === 1 ? to.name : to.pluralName
  }`;
}

export function conversionPageTitle(from: UnitDefinition, to: UnitDefinition): string {
  return `${titleCase(unitHeadingName(from))} to ${titleCase(unitHeadingName(to))} Converter`;
}

export function conversionPageDescription(from: UnitDefinition, to: UnitDefinition): string {
  // A proportional pair leads with its ratio; temperature and fuel economy lead
  // with the formula, because "1 °C = 33.8 °F" would mislead.
  const lead = hasSimpleRatio(from, to)
    ? oneUnitStatement(from, to)
    : (buildFormula(from, to)?.expression ?? null);

  return `${lead ? `${lead}. ` : ''}Convert ${pairPhrase(from, to)} instantly, with the exact formula, worked examples and a reference table.`;
}

export function buildConversionMetadata(
  pair: ConversionPair,
  from: UnitDefinition,
  to: UnitDefinition,
): Metadata {
  return buildMetadata({
    title: conversionPageTitle(from, to),
    description: conversionPageDescription(from, to),
    path: pair.path,
  });
}

export function buildCategoryMetadata(category: CategoryDefinition, unitCount: number): Metadata {
  return buildMetadata({
    title: `${category.title} Converter`,
    description: `${category.summary} Instant results, exact conversion factors and reference tables across ${unitCount} units.`,
    path: `/${category.slug}`,
  });
}

export function buildCollectionMetadata(
  collection: CollectionDefinition,
  unitCount: number,
): Metadata {
  return buildMetadata({
    title: `${collection.title} Converter`,
    description: `${collection.summary} ${unitCount} units with the exact definition for each measurement system.`,
    path: `/${collection.slug}`,
  });
}
