import type { Metadata, Viewport } from 'next';
import { GoogleAnalytics } from '@next/third-parties/google';
import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';
import { siteConfig } from '@/lib/site';
import { SiteFooter } from '@/components/navigation/SiteFooter';
import { SiteHeader } from '@/components/navigation/SiteHeader';
import { ThemeProvider, themeInitScript } from '@/components/theme/theme';
import '@/styles/globals.css';

/**
 * The site-wide sharing image generated by app/opengraph-image.tsx.
 *
 * Declared here so the defaults below carry it. A page that sets its own
 * `openGraph` object replaces the inherited file-based image, which is why
 * lib/seo/metadata.ts re-declares it for every page that does.
 */
const SOCIAL_IMAGE = {
  url: '/opengraph-image.png',
  width: 1200,
  height: 630,
  alt: `${siteConfig.name} — free online unit converter with formulas and reference tables`,
};

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.defaultTitle,
    // Page titles supply their own subject; the site name is appended here so
    // no page has to repeat it and risk an over-long, keyword-stuffed title.
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  applicationName: siteConfig.name,
  openGraph: {
    type: 'website',
    siteName: siteConfig.name,
    title: siteConfig.defaultTitle,
    description: siteConfig.description,
    url: siteConfig.url,
    locale: siteConfig.locale.replace('-', '_'),
    images: [SOCIAL_IMAGE],
  },
  twitter: {
    card: 'summary_large_image',
    title: siteConfig.defaultTitle,
    description: siteConfig.description,
    images: [SOCIAL_IMAGE.url],
  },
  // Preview and staging builds are noindexed; see siteConfig.indexable.
  robots: siteConfig.indexable
    ? { index: true, follow: true, googleBot: { index: true, follow: true } }
    : { index: false, follow: false },
  formatDetection: { telephone: false },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // Zoom is never capped: limiting it fails WCAG 1.4.4.
  colorScheme: 'light dark',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#fafafa' },
    { media: '(prefers-color-scheme: dark)', color: '#0a0a0a' },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // suppressHydrationWarning: the inline script below sets data-theme on this
    // element before React hydrates, which is the point of it.
    <html
      lang="en"
      dir="ltr"
      suppressHydrationWarning
      className={`${GeistSans.variable} ${GeistMono.variable}`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body className="flex min-h-dvh flex-col">
        <ThemeProvider>
          <a href="#main" className="skip-link">
            Skip to main content
          </a>
          <SiteHeader />
          <main id="main" className="flex-1 focus:outline-none" tabIndex={-1}>
            {children}
          </main>
          <SiteFooter />
        </ThemeProvider>
        {/*
          Nothing is requested from Google unless NEXT_PUBLIC_GA_ID is set at
          build time. With it unset the site loads no third-party script and
          sets no analytics cookie.
        */}
        {siteConfig.gaId ? <GoogleAnalytics gaId={siteConfig.gaId} /> : null}
      </body>
    </html>
  );
}
